Controllers/ForCheckAccessController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Csharpauth.Controllers
{
    [Authorize]
    public class ForCheckAccessController : Controller
    {
        [AllowAnonymous]
        //Accessible by everyone, even if users are not logged in.
        public IActionResult AllAccess()
        {
            return View();
        }

        //Accessible by logged in users.
        public IActionResult AuthorizedAccess()
        {
            return View();
        }

         [Authorize(Roles = "User")]
        //Accessible by users who have user role
        public IActionResult UserAccess()
        {
            return View();
        }

        [Authorize(Roles = "User,Admin")]
        //Accessible by users who have user role
        public IActionResult UserORAdminAccess()
        {
            return View();
        }

        [Authorize(Policy = "UserAndAdmin")]
        //Accessible by users who have user role
        public IActionResult UserANDAdminAccess()
        {
            return View();
        }

        [Authorize(Policy = "Admin")]
        //Accessible by users who have admin role
        public IActionResult AdminAccess()
        {
            return View();
        }

        [Authorize(Policy = "Admin_CreateAccess")]
        //Accessible by Admin users with a claim of create to be True
        public IActionResult Admin_CreateAccess()
        {
            return View();
        }

        [Authorize(Policy = "Admin_Create_Edit_DeleteAccess")]
        //Accessible by Admin user with claim of Create Edit and Delete (AND NOT OR)
        public IActionResult Admin_Create_Edit_DeleteAccess()
        {
            return View();
        }

        [Authorize(Policy = "Admin_Create_Edit_DeleteAccess_OR_SuperAdmin")]
        //accessible by Admin user with create, edit and delete (AND NOT OR), OR if the user role is superAdmin
        public IActionResult Admin_Create_Edit_DeleteAccess_OR_SuperAdmin()
        {
            return View();
        }

        [Authorize(Policy = "AdminWithMoreThan1000Days")]
        public IActionResult OnlyFemi()
        {
            return View();
        }

        [Authorize(Policy = "FirstNameAuth")]
        public IActionResult FirstNameAuth()
        {
            return View();
        }
    }
}

Controllers/RolesController.cs
using Csharpauth.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Csharpauth.Controllers
{
    public class RolesController: Controller
    {
         private readonly UserManager<IdentityUser> _userManager;
        private readonly AppDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            AppDbContext context
            )
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;

        }

        public IActionResult Index()
        {
            var roles = _context.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult UpdateInsert(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return View();
            }
            else
            {
                //update
                // var roles = _context.Roles.ToList();
                var objFromDb = _context.Roles.FirstOrDefault(u => u.Id == id);
                return View(objFromDb);
            }
        }

        [HttpPost]
        [Authorize(Policy = "OnlySuperAdminChecker")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateInsert(IdentityRole roleObj)
        {
            if(await _roleManager.RoleExistsAsync(roleObj.Name!))
            { 
                //error
                TempData[StaticToarst.Error] = "Role already exists.";
                return RedirectToAction(nameof(Index));
            }
            if (string.IsNullOrEmpty(roleObj.Id))
            {
                //create
                await _roleManager.CreateAsync(new IdentityRole() { Name = roleObj.Name });
                TempData[StaticToarst.Success] = "Role created successfully";
            }
            else
            {
                //update
                var objRoleFromDb = _context.Roles.FirstOrDefault(u => u.Id == roleObj.Id);
                if (objRoleFromDb == null)
                {
                    TempData[StaticToarst.Error] = "Role not found.";
                    return RedirectToAction(nameof(Index));
                }
                objRoleFromDb.Name = roleObj.Name;
                objRoleFromDb.NormalizedName = roleObj.Name!.ToUpper();
                var result = await _roleManager.UpdateAsync(objRoleFromDb);
                TempData[StaticToarst.Success] = "Role updated successfully";
            }
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        [Authorize(Policy = "OnlySuperAdminChecker")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            // for checking roles
            var objFromDb = _context.Roles.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null)
            {
                TempData[StaticToarst.Error] = "Role not found.";
                return RedirectToAction(nameof(Index));
            }
            // for checking user roles
            var userRolesForThisRole = _context.UserRoles.Where(u => u.RoleId == id).Count();
            if (userRolesForThisRole > 0)
            {
                TempData[StaticToarst.Error] = "Cannot delete this role, since there are users assigned to this role.";
                return RedirectToAction(nameof(Index));
            }
            
            // delete and return to role page
            await _roleManager.DeleteAsync(objFromDb);
            TempData[StaticToarst.Success] = "Role deleted successfully.";
            return RedirectToAction(nameof(Index));

        }
    }
}

Controllers/UserController.cs
using Csharpauth.Database;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Csharpauth.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using static Csharpauth.Models.UserClaim;
using Microsoft.AspNetCore.Authorization;

namespace Csharpauth.Controllers
{

    [Authorize (Roles = "SuperAdmin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly AppDbContext _context;

        public UserController(
            UserManager<IdentityUser> userManager,
            AppDbContext context
            )
        {
            _userManager = userManager;
            _context = context;

        }
        public IActionResult Index()
        {
            var userList = _context.AppUsers.ToList();
            var userRole = _context.UserRoles.ToList();
            var roles = _context.Roles.ToList();
            foreach(var user in userList)
            {
                var role = userRole.FirstOrDefault(u => u.UserId == user.Id);
                if (role == null)
                {
                    user.Role = "None";
                }
                else
                {
                    user.Role = roles.FirstOrDefault(u => u.Id == role.RoleId)!.Name!;
                }
            }

            return View(userList);
        }

        // for edit user by id
        public IActionResult Edit(string userId)
        {
            var objFromDb = _context.AppUsers.FirstOrDefault(user=>user.Id==userId);
            if (objFromDb == null)
            {
                return NotFound();
            }
            var userRole = _context.UserRoles.ToList();
            var roles = _context.Roles.ToList();
            var role = userRole.FirstOrDefault(user => user.UserId == objFromDb.Id);
            if (role != null)
            {
                objFromDb.RoleId = roles.FirstOrDefault(user => user.Id == role.RoleId)!.Id;
            }
            objFromDb.RoleList = _context.Roles.Select(user => new SelectListItem
            {
                Text = user.Name,
                Value = user.Id
            });
            return View(objFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AppUser user)
        {
            if (ModelState.IsValid)
            {
                var objFromDb = _context.AppUsers.FirstOrDefault(u => u.Id == user.Id);
                if (objFromDb == null)
                {
                    return NotFound();
                }
                // about the previous role
                var userRole = _context.UserRoles.FirstOrDefault(u => u.UserId == objFromDb.Id);
                if (userRole != null)
                {
                    var previousRoleName = _context.Roles.Where(u => u.Id == userRole.RoleId).Select(e => e.Name).FirstOrDefault();
                    
                    //how to remove previous role
                    await _userManager.RemoveFromRoleAsync(objFromDb, previousRoleName!);
                }

                //how to add new role
                await _userManager.AddToRoleAsync(objFromDb, _context.Roles.FirstOrDefault(u => u.Id == user.RoleId)!.Name!);
                objFromDb.Name = user.Name;
                _context.SaveChanges();
                TempData[StaticToarst.Success] = "User has been edited successfully.";
                return RedirectToAction(nameof(Index));
            }


            user.RoleList = _context.Roles.Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id
            });
            return View(user);
        }

        // for locking users
        [HttpPost]
        public IActionResult LockUnlock(string userId)
        {
            var objFromDb = _context.AppUsers.FirstOrDefault(u => u.Id == userId);
            if (objFromDb == null)
            {
                return NotFound();
            }
            if(objFromDb.LockoutEnd!=null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //user is locked and will remain locked untill lockoutend time
                //clicking on this action will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
                TempData[StaticToarst.Success] = "User unlocked successfully.";
            }
            else
            {
                //user is not locked, and we want to lock the user
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
                TempData[StaticToarst.Success] = "User locked successfully.";
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // for deleteing users
        [HttpPost]
        public IActionResult Delete(string userId)
        {
            var objFromDb = _context.AppUsers.FirstOrDefault(u => u.Id == userId);
            if (objFromDb == null)
            {
                return NotFound();
            }
            _context.AppUsers.Remove(objFromDb);
            _context.SaveChanges();
            TempData[StaticToarst.Success] = "User deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        // user claims
        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            IdentityUser user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var existingUserClaims = await _userManager.GetClaimsAsync(user); // for existingUserClaims

            var model = new UserClaim()
            {
                UserId = userId
            };

            foreach(Claim claim in UserClaimData.claimsList)
            {
                UserClaims userClaim = new UserClaims
                {
                    ClaimType = claim.Type
                };

                if (existingUserClaims.Any(c => c.Type == claim.Type)) // for existingUserClaims
                {
                    userClaim.IsSelected = true;
                }

                model.Claims.Add(userClaim);
            }

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserClaims(UserClaim userClaim)
        {
            IdentityUser user = await _userManager.FindByIdAsync(userClaim.UserId);

            if (user == null)
            {
                return NotFound();
            }

            var claims = await _userManager.GetClaimsAsync(user); // for get all the claims
            var result = await _userManager.RemoveClaimsAsync(user,claims);

            if (!result.Succeeded)
            {
                TempData[StaticToarst.Error] = "Error while removing claims";
                return View(userClaim);
            }

            result = await _userManager.AddClaimsAsync(user,
                userClaim.Claims.Where(c => c.IsSelected)
                .Select(c => new Claim(c.ClaimType, c.IsSelected.ToString()))
                );

            if (!result.Succeeded)
            {
                TempData[StaticToarst.Error] = "Error while adding claims";
                return View(userClaim);
            }

            TempData[StaticToarst.Success] = "Claims updated successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Csharpauth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Csharpauth.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
      integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Csharpauth</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartialCustom"/>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>

                        @* for check acess for different users  *@
                        <li class="nav-item dropdown">
                            <a role="button" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                ForCheckAccess
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="AllAccess">All Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="AuthorizedAccess">Authorized Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="UserAccess">User Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="UserORAdminAccess">UserORAdmin Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="UserANDAdminAccess">UserANDAdmin Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="AdminAccess">Admin Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="Admin_CreateAccess">Admin - Create only Claim Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="Admin_Create_Edit_DeleteAccess">Admin - Create,Edit & Delete Claim Access</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="Admin_Create_Edit_DeleteAccess_OR_SuperAdmin">Admin - Create,Edit & Delete Claim Access || Super Admin</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="OnlyFemi">Only Femi</a>
                                <a class="dropdown-item" asp-controller="ForCheckAccess" asp-action="FirstNameAuth">Check First Name Access</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications"/> @* // for adding to all pages *@
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Csharpauth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <div class="wrapper">
        <footer>
        <div class="footerWrapper">
            
            <div class="icons">
                <a href="https://www.linkedin.com/in/femi-adesola-oyinloye-106454145/" target="_blank" rel="noreferrer" class="linkedin">
                        <i class="fab fa-linkedin "></i>
                    </a>
                    <a href="#1" class="facebook">
                        <i class="fab fa-facebook "></i>
                    </a>
                    <a href="https://github.com/FemiAdesola" target="_blank" rel="noreferrer" class="github">
                        <i class="fab fa-github "></i>
                    </a>
                    
                </div>
               
                <p>Femi Adesola &copy; <script>document.write(new Date().getFullYear())</script> </p>
                </div>
                
        </footer>
    </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginPartialCustom.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link" href="#">Hi @UserManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
            <form id="logoutForm" method="post" class="form-inline" asp-controller="Account" asp-action="Logout">
                <button type="submit" class="btn nav-link">Logout</button>
            </form>
        </li>
    }
    else
    {
    <li class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
    </li>
    }
</ul>

Views/Shared/_Notifications.cshtml
@if (TempData[StaticToarst.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[StaticToarst.Success]');
    </script>
}
@if (TempData[StaticToarst.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[StaticToarst.Error]');
    </script>
}